name: Deploy Frontend to Homelab

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./ # <- ajuste se o docker-compose estiver em uma subpasta
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Subir Docker com build
        run: |
          docker compose down
          docker compose up -d --build
