name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 0

      - name: Deploy with Docker Compose
        run: |
          echo "🚀 Subindo containers..."
          docker compose -f docker-compose.yml down
          docker compose -f docker-compose.yml up -d --build 